apiVersion: v1
kind: Pod
metadata:
  name: emulator-pod-1
spec:
  restartPolicy: OnFailure
  containers:
  - name: emulator-pod
    image: "ubuntu:20.04"
    resources:
      limits:
        nvidia.com/mig-1g.5gb: 1
    command:
      - sh
      - -c
      -  "sleep 180"
